export default {
	"мур": "var",
	"пусть": "let",
	"если": "if",
	"иначе": "else",
	"пока": "while",
	"делай": "do",
	"для": "for",
	"попробуй": "try",
	"поймай": "catch",
	"наконец": "finally",
	"останови": "break",
	"продолжи": "continue",
	"и": "&&",
	"или": "||",
	"не": "!",
	"тип": "typeof",
	"экземпляр": "instanceof",
	"истина": "true",
	"ложь": "false",
	"ничего": "null",
	"функция": "function",
	"новый": "new",
	"верни": "return",
	"это": "this",
	"класс": "class",
	"конструктор": "constructor",
	"статический": "static",
	"наследует": "extends",
	"вызвает": "super",
	"лог": "console.log",
	"ошибка": "console.error",
	"предупреждение": "console.warn",
	"инфо": "console.info",
	"импортируй": "import",
	"из": "from",
	"экспортируй": "export",

	"когда": "switch",
	"случай": "case",
	"заверши": "break",

	"длина": "length",
	"включает": "includes",
	"раздели": "split",
	"соедини": "join",
	"добавьКСтроке": "concat",

	"абсолют": "Math.abs",
	"макс": "Math.max",
	"мин": "Math.min",
	"степень": "Math.pow",

	"вСтроку": "JSON.stringify",
	"изСтроки": "JSON.parse",
	"этоМассив": "Array.isArray",
	"Число": "Number",
	"Строка": "String",
	"Булево": "Boolean",

	"вКонтексте": "with",
	"отладка": "debugger",
	"удали": "delete",
	"ничто": "void",
//
	"Обещание": "Promise",
	"виполни": "resolve",
	"отклони": "reject",
	".затем": ".then",
	".лови": ".catch",
	".вконце": ".finally",

	"как": "as",
	"типово": "default",

	"Символ": "Symbol",
	"большоеЧисло": "BigInt",
	"неЧисло": "NaN",
	"бесконечность": "Infinity",
//
	"отфильтруй": "filter",
	"перебери": "map",
	"найди": "find",
	"каждому": "forEach",
	"добавь": "push",
	"удалиПоследний": "pop",
	"удалиПервый": "shift",
	"добавьВНачало": "unshift",
	"соединиМассивы": "concat",
	// "включает": ".includes",
	"найдиИндекс": "indexOf"
};